FROM openjdk:8-jre-alpine
COPY target/hospital-management-0.0.1-SNAPSHOT.jar /app.jar
# Inform Docker that the container is listening on the specified port at runtime.
EXPOSE 8090
ENTRYPOINT ["java","-jar","app.jar"]